version: "3.7"

services:
  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: badsecret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.27
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: name@host.com
      PGADMIN_DEFAULT_PASSWORD: badsecret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    links:
      - "db:postgres-server"

volumes:
  db-data:
  pgadmin-data:
